### PR TITLE
Adding support for arch 'darwin_arm64'

### PR DESCRIPTION
**Pull request by ynori7**
It's just the same as darwin_amd64, there's only one binary for Mac OSX currently. There is no proper darwin arm64 binary yet, but this one seems to work until we can replace it with the real thing

### CODE REVIEW

**Comment by mier85** [comment]
I assume it internally will still just use Rosetta and will not work when Rosetta is disabled, right?

**Comment by ynori7** [comment]
I don't really know. @doubtx do you happen to know anything about Rosetta?

**Review by manit-kumar — APPROVED** [review]

**Comment by klipach** [comment]
I'm using `protoc` on mac M1 it works via Rosetta, there are no issues.

I did the switch to darwin_amd64 using `export GOARCH=amd64`

**Comment by ynori7** [comment]
Not necessary anymore as there's now official support.

**Pull request closed without merging**
